apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain1-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: bharathikalai/app1:latest  # Replace with your image
          ports:
            - containerPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain2-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: bharathikalai/app2:latest  # Replace with your image
          ports:
            - containerPort: 8081
