apiVersion: v1
kind: Service
metadata:
  name: domain-app1-service
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30001  # Optional: specify a fixed port or leave it to auto-assign

---
apiVersion: v1
kind: Service
metadata:
  name: domain-app2-service
spec:
  type: NodePort
  selector:
    app: app2
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30002  # Optional: specify a fixed port or leave it to auto-assign
